CREATE TABLE "campaign_enrollment_profiles" (
	"id" serial PRIMARY KEY NOT NULL,
	"campaign_enrollment_id" integer NOT NULL,
	"profile_id" text NOT NULL,
	"first_name" text NOT NULL,
	"last_name" text NOT NULL,
	"full_name" text NOT NULL,
	"job_title" text NOT NULL,
	"department" text,
	"management_level" text,
	"seniority_level" text,
	"is_decision_maker" boolean DEFAULT false,
	"email" text,
	"phone" text,
	"linkedin_url" text,
	"city" text NOT NULL,
	"state" text NOT NULL,
	"country" text NOT NULL,
	"company_id" text,
	"company_name" text NOT NULL,
	"company_industry" text,
	"company_size" integer,
	"company_size_range" text,
	"company_revenue" text,
	"company_description" text,
	"company_domain" text,
	"company_founded" integer,
	"tenure_months" integer,
	"recent_job_change" boolean DEFAULT false,
	"confidence" integer,
	"data_source" text DEFAULT 'coresignal' NOT NULL,
	"last_enriched" timestamp,
	"enrolled_at" timestamp DEFAULT now() NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "campaign_profile_operations" (
	"id" serial PRIMARY KEY NOT NULL,
	"enrollment_profile_id" integer NOT NULL,
	"email_status" text DEFAULT 'pending' NOT NULL,
	"last_email_sent" timestamp,
	"emails_sent_count" integer DEFAULT 0 NOT NULL,
	"response_status" text DEFAULT 'none' NOT NULL,
	"first_response_date" timestamp,
	"last_response_date" timestamp,
	"open_count" integer DEFAULT 0 NOT NULL,
	"click_count" integer DEFAULT 0 NOT NULL,
	"reply_count" integer DEFAULT 0 NOT NULL,
	"current_sequence_step" integer DEFAULT 1 NOT NULL,
	"next_scheduled_contact" timestamp,
	"last_contact_attempt" timestamp,
	"is_active" text DEFAULT 'true' NOT NULL,
	"unsubscribed_at" timestamp,
	"paused_at" timestamp,
	"pause_reason" text,
	"notes" text,
	"manual_tags" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "campaign_enrollment_profiles" ADD CONSTRAINT "campaign_enrollment_profiles_campaign_enrollment_id_campaign_enrollments_id_fk" FOREIGN KEY ("campaign_enrollment_id") REFERENCES "public"."campaign_enrollments"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "campaign_profile_operations" ADD CONSTRAINT "campaign_profile_operations_enrollment_profile_id_campaign_enrollment_profiles_id_fk" FOREIGN KEY ("enrollment_profile_id") REFERENCES "public"."campaign_enrollment_profiles"("id") ON DELETE cascade ON UPDATE no action;