CREATE TABLE "target_list_profiles" (
	"id" serial PRIMARY KEY NOT NULL,
	"target_list_id" integer NOT NULL,
	"profile_id" text NOT NULL,
	"first_name" text NOT NULL,
	"last_name" text NOT NULL,
	"full_name" text NOT NULL,
	"job_title" text NOT NULL,
	"department" text,
	"management_level" text,
	"seniority_level" text,
	"is_decision_maker" boolean DEFAULT false,
	"email" text,
	"phone" text,
	"linkedin_url" text,
	"city" text NOT NULL,
	"state" text NOT NULL,
	"country" text NOT NULL,
	"company_id" text,
	"company_name" text NOT NULL,
	"company_industry" text,
	"company_size" integer,
	"company_size_range" text,
	"company_revenue" text,
	"company_description" text,
	"company_domain" text,
	"company_founded" integer,
	"tenure_months" integer,
	"recent_job_change" boolean DEFAULT false,
	"confidence" integer,
	"data_source" text DEFAULT 'coresignal' NOT NULL,
	"last_enriched" timestamp,
	"apollo_prospect_id" text,
	"additional_data" json DEFAULT '{}'::json,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"last_synced" timestamp
);
--> statement-breakpoint
ALTER TABLE "target_list_profiles" ADD CONSTRAINT "target_list_profiles_target_list_id_target_lists_id_fk" FOREIGN KEY ("target_list_id") REFERENCES "public"."target_lists"("id") ON DELETE cascade ON UPDATE no action;