ALTER TABLE "target_list_profiles" DROP COLUMN "profile_id";--> statement-breakpoint
ALTER TABLE "target_list_profiles" DROP COLUMN "first_name";--> statement-breakpoint
ALTER TABLE "target_list_profiles" DROP COLUMN "last_name";--> statement-breakpoint
ALTER TABLE "target_list_profiles" DROP COLUMN "full_name";--> statement-breakpoint
ALTER TABLE "target_list_profiles" DROP COLUMN "job_title";--> statement-breakpoint
ALTER TABLE "target_list_profiles" DROP COLUMN "department";--> statement-breakpoint
ALTER TABLE "target_list_profiles" DROP COLUMN "management_level";--> statement-breakpoint
ALTER TABLE "target_list_profiles" DROP COLUMN "seniority_level";--> statement-breakpoint
ALTER TABLE "target_list_profiles" DROP COLUMN "is_decision_maker";--> statement-breakpoint
ALTER TABLE "target_list_profiles" DROP COLUMN "email";--> statement-breakpoint
ALTER TABLE "target_list_profiles" DROP COLUMN "phone";--> statement-breakpoint
ALTER TABLE "target_list_profiles" DROP COLUMN "linkedin_url";--> statement-breakpoint
ALTER TABLE "target_list_profiles" DROP COLUMN "city";--> statement-breakpoint
ALTER TABLE "target_list_profiles" DROP COLUMN "state";--> statement-breakpoint
ALTER TABLE "target_list_profiles" DROP COLUMN "country";--> statement-breakpoint
ALTER TABLE "target_list_profiles" DROP COLUMN "company_id";--> statement-breakpoint
ALTER TABLE "target_list_profiles" DROP COLUMN "company_name";--> statement-breakpoint
ALTER TABLE "target_list_profiles" DROP COLUMN "company_industry";--> statement-breakpoint
ALTER TABLE "target_list_profiles" DROP COLUMN "company_size";--> statement-breakpoint
ALTER TABLE "target_list_profiles" DROP COLUMN "company_size_range";--> statement-breakpoint
ALTER TABLE "target_list_profiles" DROP COLUMN "company_revenue";--> statement-breakpoint
ALTER TABLE "target_list_profiles" DROP COLUMN "company_description";--> statement-breakpoint
ALTER TABLE "target_list_profiles" DROP COLUMN "company_domain";--> statement-breakpoint
ALTER TABLE "target_list_profiles" DROP COLUMN "company_founded";--> statement-breakpoint
ALTER TABLE "target_list_profiles" DROP COLUMN "tenure_months";--> statement-breakpoint
ALTER TABLE "target_list_profiles" DROP COLUMN "recent_job_change";--> statement-breakpoint
ALTER TABLE "target_list_profiles" DROP COLUMN "confidence";--> statement-breakpoint
ALTER TABLE "target_list_profiles" DROP COLUMN "data_source";--> statement-breakpoint
ALTER TABLE "target_list_profiles" DROP COLUMN "last_enriched";--> statement-breakpoint
ALTER TABLE "target_list_profiles" DROP COLUMN "apollo_prospect_id";--> statement-breakpoint
ALTER TABLE "target_list_profiles" DROP COLUMN "additional_data";--> statement-breakpoint
ALTER TABLE "target_list_profiles" DROP COLUMN "created_at";