import { Profile } from "@/types/profile";

export const mapProfileToTargetList = (profile: Profile, targetListId: number) => ({
  targetListId,
  profileId: profile.id,
  firstName: profile.firstName,
  lastName: profile.lastName,
  fullName: profile.fullName,
  jobTitle: profile.jobTitle,
  department: profile.department || null,
  managementLevel: profile.managementLevel || null,
  seniorityLevel: profile.seniorityLevel || null,
  isDecisionMaker: profile.isDecisionMaker || false,
  email: profile.email || null,
  phone: profile.phone || null,
  linkedinUrl: profile.linkedinUrl || null,
  city: profile.city,
  state: profile.state,
  country: profile.country,
  companyId: profile.company?.id || null,
  companyName: profile.company?.name || '',
  companyIndustry: profile.company?.industry || null,
  companySize: profile.company?.employeeCount || null,
  companySizeRange: profile.company?.employeeCountRange || null,
  companyRevenue: profile.company?.revenue || null,
  companyDescription: profile.company?.description || null,
  companyDomain: profile.company?.domain || null,
  companyFounded: profile.company?.foundedYear || null,
  tenureMonths: profile.currentTenure?.monthsInRole || null,
  recentJobChange: false,
  confidence: profile.confidence ? Math.round(profile.confidence * 100) : null,
  dataSource: profile.dataSource || 'coresignal',
  lastEnriched: profile.lastUpdated ? new Date(profile.lastUpdated) : null,
  apolloProspectId: profile.id,
  additionalData: profile,
});